pipeline{
    agent any
    stages{
        stage('Checking Make version'){
            steps{
            sh 'make --version'
            }
        }
        stage('Running echo') {
             steps {
                 sh """
                    pwd
                    echo "Printing this message from dev branch on ${env.BUILD_NUMBER}"
                   """
              }
          }


        stage('Echoing message'){
            when{
                    branch 'dev'
                }
            steps{
                script{
                    sh "echo Echoing from ${env.BRANCH_NAME} in ${env.NODE_NAME}"
                }
            }
        }
    }
}
