pipeline{
    agent any
    stages{
        stage('Checking Make version'){
            steps{
            sh 'make --version'
            }
        }
        stage('Running makefile'){
            steps{
            sh 'pwd'
            dir('/var/lib/jenkins/workspace/make/lab-1'){
            sh 'make'
            }
            }
        }
    }
}