pipeline{
    agent any
    stages{
        stage('Checking Make version'){
            steps{
            sh 'make --version'
            }
        }
        stage('Running makefile'){
            steps{
            sh 'make'
            }
        }
    }
}